cargo-features = ["profile-rustflags"]

[package]
name = "rustos"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m = "0.7"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
debug = true      # <- this ensures debug symbols are included
